name: NodeJS with Webpack tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout #检出
              uses: actions/checkout@master #检出的依赖
              with:
                persist-credentials: false #不保存证书
            - name: Cache Node Dependencies
              id: cache
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{runner.os}}-npm-caches-${{ hashFiles('package-lock.json')}}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
               npm install --force
            - name: test Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
               cd ./test/smoke/template
               npm  install --force
            - name: Test
              run: npm test
